export const SAVE_CONSOLE_STATE = 'SAVE_CONSOLE_STATE';
export const CLEAR_CURRENT_CONSOLE = 'CLEAR_CURRENT_CONSOLE';
export const ADD_ROUTE_TO_TABLE = 'ADD_ROUTE_TO_TABLE';
export const SEND_PING = 'SEND_PING';
export const ADD_TERMINAL = 'ADD_TERMINAL';
